#!/bin/bash
Tmp=/tmp/BIB$$
trap 'exit 0' INT HUP QUIT TERM ALRM USR1
trap 'rm -f "$Tmp"' EXIT
rm -f "$Tmp"  >/dev/null 2>&1

programname=bib
function usage {
    echo ""
    echo "usage: $programname [-pgrlih] [-n name] [-v value]"
    echo "  -p             put a name/value pair"
    echo "  -g             get the value of a name"
    echo "  -r             remove a name/value pair"
    echo "  -l             list all name/value pairs"
    echo "  -i             initial the name/pair dataset (empty it)"
    echo "  -n <name>      specify a name"
    echo "  -v <value>     specify a value"
    echo "  -h             display help"
    exit 1
}
DBFILE="bib.db"
touch $DBFILE

while getopts "n:v:gplrih" arg
do
  case $arg in
     n) NAME=$OPTARG
        ;;
     v) VALUE=$OPTARG
        ;;
     g) 
        cat "$DBFILE" | gawk -v tmp=$Tmp -v dbfile="$DBFILE" -v n="$NAME" -v v="$VALUE" -F, ' {value[$1] = $2;}
        END {
            sz ="NULL"; if (n in value) sz=value[n]; print sz;
        }'
        ;;
     p) 
        cat "$DBFILE" | gawk -v dbfile="$DBFILE" -v n="$NAME" -v v="$VALUE" -F, ' {value[$1] = $2;}
        END {
            value[n]=v;
            OFS=","; system("rm -rf " dbfile); 
            for (name in value) {
                print name,value[name] >> dbfile;
                close(dbfile); 
            }
        }'
        ;;
     l) 
        cat "$DBFILE" | gawk -v dbfile="$DBFILE" -v n="$NAME" -v v="$VALUE" -F, ' {value[$1] = $2;}
        END {
            OFS=","; for (name in value) { print name,value[name];  }
        }'
        ;;
     r) 
        cat "$DBFILE" | gawk -v dbfile="$DBFILE" -v n="$NAME" -v v="$VALUE" -F, ' {value[$1] = $2;}
        END {
            value[n]=v;
            OFS=","; system("rm -rf " dbfile); for (name in value) { if (n!=name) print name,value[name] >> dbfile; close(dbfile); }
        }'
        ;;
     i) 
        cat "$DBFILE" | gawk -v dbfile="$DBFILE" -v n="$NAME" -v v="$VALUE" -F, '
        END {
            system("rm -rf " dbfile); 
        }'
        ;;
     h) usage
        ;;
     *) exit 0
        ;;
  esac
done
shift $(($OPTIND - 1))




